CREATE TABLE TBL_GENERA_PACKING
(
	Id_Packing INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Fecha_Creacion DATETIME NULL,
	Estatus VARCHAR(15) NULL,
	Fecha_Conclucion DATETIME NULL
	
)
-- SELECT * FROM TBL_GENERA_PACKING
-- DELETE TBL_GENERA_PACKING
-- DROP TABLE TBL_GENERA_PACKING 
-- SP_HELP TBL_GENERA_PACKING


CREATE TABLE TBL_PACKING_ORDEN
(
	Id_Orden INT NOT NULL,
	Id_Packing INT NOT NULL
	
)
-- SELECT * FROM TBL_PACKING_ORDEN
-- DELETE TBL_PACKING_ORDEN
-- DROP TABLE TBL_PACKING_ORDEN
-- SP_HELP TBL_PACKING_ORDEN

CREATE TABLE TBL_PRECINTO_PACKING
(
	Id_PreCinto VARCHAR(100) NULL,
	Id_Packing INT NULL,
	Id_Caja INT NULL
)

-- SELECT * FROM TBL_PRECINTO_PACKING
-- DELETE TBL_PRECINTO_PACKING
-- DROP TABLE TBL_PRECINTO_PACKING
-- SP_HELP TBL_PRECINTO_PACKING


CREATE TABLE TBL_PACKING_DETALLE
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Id_Caja] [int] NOT NULL,
	[Id_Packing] [int] NULL,
	[Id_Orden] [int] NOT NULL,
	[Art] [varchar](20) NULL,
	[SubCuenta] [varchar](20) NULL,
	[Cantidad] [int] NULL,
	[Escaneados] [int] NULL,
	[Codigo] [varchar](20) NULL
	
)
-- SELECT * FROM TBL_PACKING_DETALLE
-- DELETE TBL_PACKING_DETALLE
-- DROP TABLE TBL_PACKING_DETALLE
-- SP_HELP TBL_PACKING_DETALLE

CREATE TABLE TBL_PACKING_BOX
(
	Id_Caja INT PRIMARY KEY NOT NULL,
	Id_Packing INT NOT NULL,
	Dimeniones VARCHAR(50),
	Tara DECIMAL(10,2),
	Peso DECIMAL(10,2),
	Estatus VARCHAR(20)
)
-- SELECT * FROM TBL_PACKING_BOX
-- DELETE TBL_PACKING_BOX
-- DROP TABLE TBL_PACKING_BOX
-- SP_HELP TBL_PACKING_BOX

